<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <Company>Panoramic Data Limited</Company>
    <Authors>Panoramic Data Limited</Authors>
    <Product>ChartMagic</Product>
    <Description>ChartMagic: A .NET 9 library for advanced chart rendering and manipulation.</Description>
    <PackageTags>ChartMagic;chart;graphics;svg;rendering;visualization</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/panoramicdata/PanoramicData.ChartMagic</PackageProjectUrl>
    <RepositoryUrl>https://github.com/panoramicdata/PanoramicData.ChartMagic</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageIcon>Panoramic Data.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Copyright>Copyright © Panoramic Data Limited 2025</Copyright>
    <PackageReleaseNotes>
			Updated to .NET 9.0.
			Removed the dependency on GDI+, for cross-platform support.
		</PackageReleaseNotes>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageId>PanoramicData.ChartMagic</PackageId>
    <NeutralResourcesLanguage>en</NeutralResourcesLanguage>
    <NoWarn>$(NoWarn);CS1587;CS1591</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Include="LICENSE" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="" />
    <None Include="Panoramic Data.png" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="Svg.Skia" />
    <PackageReference Include="Nerdbank.GitVersioning">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Svg" />
  </ItemGroup>
</Project>