global using FluentAssertions;
global using PanoramicData.ChartMagic.Extensions;
global using PanoramicData.ChartMagic.Models;
global using PanoramicData.ChartMagic.Test.Models;
global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using Xunit;